services:
    pgsql:
        image: 'postgres:18-alpine'
        ports:
            - '${FORWARDPGPORT:-5432}:5432'
        environment:
            PGPASSWORD: '${PGPASSWORD:-secret}'
            POSTGRES_DB: '${PGDATABASE:-metrics}'
            POSTGRES_USER: '${PGUSER:-metrics}'
            POSTGRES_PASSWORD: '${PGPASSWORD:-secret}'
        volumes:
            - 'pgsql:/var/lib/postgresql'
            - './docker/pgsql/create-testing-database.sql:/docker-entrypoint-initdb.d/10-create-testing-database.sql'
        networks:
            - pgsql
        healthcheck:
            test: [ CMD, pg_isready, '-q', '-d', '${PGDATABASE:-metrics}', '-U', '${PGUSER:-metrics}' ]
            retries: 3
            timeout: 5s
networks:
    pgsql:
        driver: bridge
volumes:
    pgsql:
        driver: local
