package resetgen

import (
	"bytes"
	"fmt"
	"go/ast"
	"go/build"
	"go/parser"
	"go/token"
	"go/types"
	"io/fs"
	"os"
	"path/filepath"
	"slices"
	"strings"

	"golang.org/x/tools/go/packages"
)

const (
	genFile   = "reset.gen.go"
	genHeader = "// Code generated by cmd/reset; DO NOT EDIT."
)

type generation struct {
	files    map[string][]byte
	obsolete []string
}

// Run generates Reset methods for packages matching pattern and updates generated files.
func Run(pattern string) error {
	result, err := generate(pattern)
	if err != nil {
		return err
	}

	for path, src := range result.files {
		if err := os.WriteFile(path, src, 0o644); err != nil {
			return err
		}
	}
	for _, path := range result.obsolete {
		if err := os.Remove(path); err != nil && !os.IsNotExist(err) {
			return err
		}
	}

	return nil
}

func generate(pattern string) (*generation, error) {
	fset := token.NewFileSet()
	pkgs, metadata, err := loadPackages(pattern, fset)
	if err != nil {
		return nil, err
	}

	structs := make(map[*packages.Package][]*types.Named)
	marked := make(map[*types.TypeName]bool)
	constraints := newConstraintChecker(fset, pkgs, metadata)
	for _, pkg := range pkgs {
		for _, n := range markedStructs(pkg) {
			if err := constraints.checkType(n); err != nil {
				return nil, fmt.Errorf("%s: %s: %w", pkg.PkgPath, n.Obj().Name(), err)
			}
			if err := checkResetName(n); err != nil {
				return nil, fmt.Errorf("%s: %w", pkg.PkgPath, err)
			}
			if err := constraints.checkGeneratedMethods(n); err != nil {
				return nil, fmt.Errorf("%s: %w", pkg.PkgPath, err)
			}
			structs[pkg] = append(structs[pkg], n)
			marked[n.Obj()] = true
		}
	}

	result := &generation{files: make(map[string][]byte)}
	dispatches := make(map[resetTypeID][]int)
	context := &generationContext{
		marked:      marked,
		constraints: constraints,
		metadata:    metadata,
		dispatches:  dispatches,
	}
	for _, pkg := range pkgs {
		if pkg.Dir == "" {
			continue
		}
		path := filepath.Join(pkg.Dir, genFile)
		existing, err := os.ReadFile(path)
		if err != nil && !os.IsNotExist(err) {
			return nil, fmt.Errorf("%s: %w", path, err)
		}
		owned := hasGenHeader(existing)
		list := structs[pkg]
		if len(list) == 0 {
			if owned {
				result.obsolete = append(result.obsolete, path)
			}
			continue
		}
		if err == nil && !owned {
			return nil, fmt.Errorf("%s: файл не принадлежит генератору", path)
		}

		src, err := resetFile(pkg, list, context)
		if err != nil {
			return nil, fmt.Errorf("%s: %w", pkg.PkgPath, err)
		}

		result.files[path] = src
	}

	if err := checkGenericResets(pattern, result, pkgs, metadata, dispatches); err != nil {
		return nil, err
	}
	return result, nil
}

func loadPackages(pattern string, fset *token.FileSet) ([]*packages.Package, []*packages.Package, error) {
	discoveryConfig := &packages.Config{
		Mode: packages.NeedName | packages.NeedFiles,
	}
	pkgs, err := packages.Load(discoveryConfig, pattern)
	if err != nil {
		return nil, nil, err
	}
	rootDirs := make(map[string]bool)
	overlay := make(map[string][]byte)
	for _, pkg := range pkgs {
		if pkg.Dir == "" {
			continue
		}
		rootDirs[pkg.Dir] = true
		path := filepath.Join(pkg.Dir, genFile)
		src, err := os.ReadFile(path)
		if os.IsNotExist(err) {
			continue
		}
		if err != nil {
			return nil, nil, fmt.Errorf("%s: %w", path, err)
		}
		if !hasGenHeader(src) {
			continue
		}
		packagePath, packageSource := path, any(src)
		for _, sourcePath := range pkg.GoFiles {
			if sourcePath != path {
				packagePath, packageSource = sourcePath, nil
				break
			}
		}
		file, err := parser.ParseFile(fset, packagePath, packageSource, parser.PackageClauseOnly)
		if err != nil {
			return nil, nil, err
		}
		overlay[path] = []byte(genHeader + "\n\npackage " + file.Name.Name + "\n")
	}
	metadataConfig := &packages.Config{
		Mode: packages.NeedName | packages.NeedFiles | packages.NeedCompiledGoFiles |
			packages.NeedImports | packages.NeedDeps,
		Tests:   true,
		Overlay: overlay,
	}
	metadata, err := packages.Load(metadataConfig, pattern)
	if err != nil {
		return nil, nil, err
	}
	if err := checkPackageErrors(metadata, packages.TypeError); err != nil {
		return nil, nil, err
	}
	typedConfig := &packages.Config{
		Mode: packages.NeedName | packages.NeedFiles | packages.NeedSyntax |
			packages.NeedTypes | packages.NeedTypesInfo | packages.NeedImports,
		Fset:    fset,
		Overlay: overlay,
		ParseFile: func(fset *token.FileSet, name string, src []byte) (*ast.File, error) {
			if rootDirs[filepath.Dir(name)] {
				return parseFile(fset, name, src)
			}
			return parser.ParseFile(fset, name, src, parser.AllErrors|parser.ParseComments)
		},
	}
	pkgs, err = packages.Load(typedConfig, pattern)
	if err != nil {
		return nil, nil, err
	}
	if err := checkPackageErrors(pkgs, packages.TypeError, packages.ListError); err != nil {
		return nil, nil, err
	}

	return pkgs, metadata, nil
}

func checkPackageErrors(pkgs []*packages.Package, ignored ...packages.ErrorKind) error {
	for pkg := range packages.Postorder(pkgs) {
		for _, err := range pkg.Errors {
			if !slices.Contains(ignored, err.Kind) {
				return fmt.Errorf("%s: %w", pkg.PkgPath, err)
			}
		}
	}

	return nil
}

func hasGenHeader(src []byte) bool {
	return bytes.HasPrefix(src, []byte(genHeader+"\n")) || bytes.HasPrefix(src, []byte(genHeader+"\r\n"))
}

func checkBuildConstraints(path string) error {
	info, err := os.Stat(path)
	if err != nil {
		return err
	}

	ctx := build.Default
	ctx.UseAllFiles = true
	ctx.CgoEnabled = true
	ctx.ReadDir = func(string) ([]fs.FileInfo, error) {
		return []fs.FileInfo{info}, nil
	}
	pkg, err := ctx.ImportDir(filepath.Dir(path), 0)
	if err != nil {
		return err
	}
	if len(pkg.AllTags) > 0 {
		return fmt.Errorf("ограничения сборки не поддерживаются: %s", strings.Join(pkg.AllTags, ", "))
	}

	return nil
}

func parseFile(fset *token.FileSet, name string, src []byte) (*ast.File, error) {
	mode := parser.AllErrors | parser.ParseComments
	if filepath.Base(name) == genFile && hasGenHeader(src) {
		mode = parser.PackageClauseOnly
	}

	return parser.ParseFile(fset, name, src, mode)
}

func markedStructs(pkg *packages.Package) []*types.Named {
	var res []*types.Named
	for _, file := range pkg.Syntax {
		for _, decl := range file.Decls {
			gd, ok := decl.(*ast.GenDecl)
			if !ok || gd.Tok != token.TYPE {
				continue
			}

			for _, spec := range gd.Specs {
				ts := spec.(*ast.TypeSpec)
				obj := pkg.TypesInfo.Defs[ts.Name]
				if obj == nil {
					continue
				}

				t := obj.Type()
				n, named := t.(*types.Named)
				_, isStruct := t.Underlying().(*types.Struct)
				if named && isStruct && (hasMarker(gd.Doc) || hasMarker(ts.Doc)) {
					res = append(res, n)
				}
			}
		}
	}

	return res
}

func hasMarker(doc *ast.CommentGroup) bool {
	return slices.Contains(strings.Split(doc.Text(), "\n"), "generate:reset")
}

func checkResetName(n *types.Named) error {
	for field := range n.Underlying().(*types.Struct).Fields() {
		if field.Name() == resetMethodName || field.Name() == resetWithVisitedMethodName {
			return fmt.Errorf("%s.%s: поле конфликтует с генерируемым методом", n.Obj().Name(), field.Name())
		}
	}
	for method := range n.Methods() {
		if method.Name() == resetMethodName || method.Name() == resetWithVisitedMethodName {
			return fmt.Errorf("%s.%s: метод уже объявлен", n.Obj().Name(), method.Name())
		}
	}

	return nil
}
