package resetgen

import (
	"os"
	"strings"
	"testing"
)

func TestRunWritesGeneratedFiles(t *testing.T) {
	dir := t.TempDir()
	writeFixtureFile(t, dir, "go.mod", "module example.com/resetgen-run\n\ngo 1.25.8\n")
	writeFixtureFile(t, dir, "source.go", `package fixture

// generate:reset
type Value struct { Number int }
`)

	previous, err := os.Getwd()
	if err != nil {
		t.Fatal(err)
	}
	if err := os.Chdir(dir); err != nil {
		t.Fatal(err)
	}
	t.Cleanup(func() {
		if err := os.Chdir(previous); err != nil {
			t.Errorf("restore working directory: %v", err)
		}
	})

	if err := Run("./..."); err != nil {
		t.Fatalf("Run() вернул ошибку: %v", err)
	}

	generated := readFixtureFile(t, dir, "reset.gen.go")
	for _, want := range []string{
		"// Code generated by cmd/reset; DO NOT EDIT.",
		"func (v *Value) Reset()",
		"func (v *Value) ResetWithVisited(",
	} {
		if !strings.Contains(string(generated), want) {
			t.Errorf("сгенерированный файл не содержит %q:\n%s", want, generated)
		}
	}
}
