// Code generated by cmd/reset; DO NOT EDIT.

package example

import resetReflect "reflect"

// Reset сбрасывает ResetableStruct к начальному состоянию.
func (r *ResetableStruct) Reset() {
	if r == nil {
		return
	}
	r.ResetWithVisited(map[interface{}]struct{}{}, r)
}

// ResetWithVisited продолжает сброс с общей картой посещённых объектов.
// original сохраняет вызов пользовательского Reset при встраивании типа.
// Тип необязательного параметра отличает собственный протокол от унаследованного.
func (r *ResetableStruct) ResetWithVisited(resetVisited map[interface{}]struct{}, resetOriginal interface{ Reset() }, _ ...*ResetableStruct) {
	if resetOriginal == nil {
		return
	}
	if resetOriginal != r {
		resetOriginal.Reset()
		return
	}
	if r == nil {
		return
	}
	if resetVisited == nil {
		resetVisited = map[interface{}]struct{}{}
	}
	if _, resetSeen := resetVisited[r]; resetSeen {
		return
	}
	resetVisited[r] = struct{}{}

	r.i = 0
	r.str = ""
	if r.strP != nil {
		*r.strP = ""
	}
	r.s = r.s[:0]
	clear(r.m)
	if r.child != nil {
		(*r.child).ResetWithVisited(resetVisited, &(*r.child))
	}
}

// Reset сбрасывает Wrapper к начальному состоянию.
func (w *Wrapper) Reset() {
	if w == nil {
		return
	}
	w.ResetWithVisited(map[interface{}]struct{}{}, w)
}

// ResetWithVisited продолжает сброс с общей картой посещённых объектов.
// original сохраняет вызов пользовательского Reset при встраивании типа.
// Тип необязательного параметра отличает собственный протокол от унаследованного.
func (w *Wrapper) ResetWithVisited(resetVisited2 map[interface{}]struct{}, resetOriginal2 interface{ Reset() }, _ ...*Wrapper) {
	if resetOriginal2 == nil {
		return
	}
	if resetOriginal2 != w {
		resetOriginal2.Reset()
		return
	}
	if w == nil {
		return
	}
	if resetVisited2 == nil {
		resetVisited2 = map[interface{}]struct{}{}
	}
	if _, resetSeen2 := resetVisited2[w]; resetSeen2 {
		return
	}
	resetVisited2[w] = struct{}{}

	w.rs.ResetWithVisited(resetVisited2, &(w.rs))
	resetValue(&(w.buf), resetVisited2)
	resetZero(&(w.at))
	if w.names != nil {
		*w.names = (*w.names)[:0]
	}
	w.kind = ""
	w.b = false
	w.f = 0
	if w.pp != nil {
		if *w.pp != nil {
			(**w.pp).ResetWithVisited(resetVisited2, &(**w.pp))
		}
	}
	if w.pm != nil {
		clear(*w.pm)
	}
	if w.pt != nil {
		resetZero(&(*w.pt))
	}
	resetZero(&(w.emb))
	resetZero(&(w.plain))
}

// Reset сбрасывает InGroup к начальному состоянию.
func (i *InGroup) Reset() {
	if i == nil {
		return
	}
	i.n = 0
}

func resetZero[T interface{}](value *T) {
	var zero T
	*value = zero
}
func resetValue(value interface{ Reset() }, visited map[interface{}]struct{}) {
	if value == nil {
		return
	}
	v := resetReflect.ValueOf(value)
	switch v.Kind() {
	case resetReflect.Chan, resetReflect.Func, resetReflect.Map, resetReflect.Pointer, resetReflect.Slice:
		if v.IsNil() {
			return
		}
	}
	if resetter, ok := value.(interface {
		ResetWithVisited(map[interface{}]struct{}, interface{ Reset() })
	}); ok {
		resetter.ResetWithVisited(visited, value)
		return
	}
	if method := v.MethodByName("ResetWithVisited"); method.IsValid() {
		signature := method.Type()
		if signature.NumIn() == 3 && signature.NumOut() == 0 && signature.IsVariadic() &&
			signature.In(0) == resetReflect.TypeFor[map[interface{}]struct{}]() &&
			signature.In(1) == resetReflect.TypeFor[interface{ Reset() }]() &&
			signature.In(2) == resetReflect.SliceOf(v.Type()) {
			method.Call([]resetReflect.Value{resetReflect.ValueOf(visited), v})
			return
		}
	}
	value.Reset()
}
