// Code generated by cmd/reset; DO NOT EDIT.

package metrics

// Reset сбрасывает Metrics к начальному состоянию.
func (m *Metrics) Reset() {
	if m == nil {
		return
	}
	m.ResetWithVisited(map[interface{}]struct{}{}, m)
}

// ResetWithVisited продолжает сброс с общей картой посещённых объектов.
// original сохраняет вызов пользовательского Reset при встраивании типа.
// Тип необязательного параметра отличает собственный протокол от унаследованного.
func (m *Metrics) ResetWithVisited(resetVisited map[interface{}]struct{}, resetOriginal interface{ Reset() }, _ ...*Metrics) {
	if resetOriginal == nil {
		return
	}
	if resetOriginal != m {
		resetOriginal.Reset()
		return
	}
	if m == nil {
		return
	}
	if resetVisited == nil {
		resetVisited = map[interface{}]struct{}{}
	}
	if _, resetSeen := resetVisited[m]; resetSeen {
		return
	}
	resetVisited[m] = struct{}{}

	m.ID = ""
	m.MType = ""
	if m.Delta != nil {
		*m.Delta = 0
	}
	if m.Value != nil {
		*m.Value = 0
	}
	m.Hash = ""
}
