// Code generated by cmd/reset; DO NOT EDIT.

package metrics

// Reset сбрасывает Metrics к начальному состоянию.
func (m *Metrics) Reset() {
	if m == nil {
		return
	}
	m.ID = ""
	m.MType = ""
	if m.Delta != nil {
		*m.Delta = 0
	}
	if m.Value != nil {
		*m.Value = 0
	}
	m.Hash = ""
}
